Task 3 Add Martian weather on a Curiosity mission sol
rajsuman-choubey/MillomSandBox pull request #3
Opened 2022-08-03 14:13 UTC by rajsuman-choubey

Mars weather on a Curiosity mission sol.

2022-08-05 08:06 UTC, TrondTelenor requested changes
Good work, got a few comments though..

2022-08-05 08:06 UTC, TrondT commented on src/main/java/millom/sandbox/MessageService.java
> +package millom.sandbox;
I would rather make the package-name more specific, e.g. millom.sandbox.nasa.weather or something.
Package names should in general reflect something about the features/functions.
Not a blocker though.

2022-08-05 08:06 UTC, TrondT commented on src/main/java/millom/sandbox/pojo/Descriptions.java
> +    public DescriptionsBuilder(String disclaimerEn, String disclaimerEs, String sol_desc_en,
A single constructor with a million parameters is really what a builder-pattern is used for to avoid.
https://medium.com/@ajinkyabadve/builder-design-patterns-in-java-1ffb12648850

2022-08-05 08:06 UTC, TrondT commented on src/main/java/millom/sandbox/pojo/Sol.java
> +    public SolBuilder(String id, String terrestrialDate, String sol, String ls, String season,
Same as before.

2022-08-05 08:06 UTC, TrondT commented on src/main/java/millom/sandbox/MyApp.java
> +      System.out.println(String.format("Application started.%nStop the application using CTRL+C"));
No need to format, it is a plain string. Remove %n.

2022-08-05 08:06 UTC, TrondTelenor commented on src/test/java/millom/sandbox/Utility/WeatherDataUtility.java
> +  private static final Descriptions DESCRIPTIONS = new Descriptions.DescriptionsBuilder("\\t    \\n\\t\\t\\tThe information contained into this file is provided by Centro de Astrobiologia\\n\\t\\t\\t
Such constructs are quite hard to maintain. With a proper builder it would be easier to both read and maintain.

2022-08-05 12:31 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/MyApp.java
> +      System.out.println(String.format("Application started.%nStop the application using CTRL+C"));
Remove %n.
`"Application started and use CTRL+C to Stop the application"`

2022-08-07 16:48 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/pojo/Descriptions.java
> +    public DescriptionsBuilder(String disclaimerEn, String disclaimerEs, String sol_desc_en,
` public DescriptionsBuilder disclaimerEn(String disclaimerEn) {
      this.disclaimerEn = disclaimerEn;
      return this;
    }

    public DescriptionsBuilder disclaimerEs(String disclaimerEs) {
      this.disclaimerEs = disclaimerEs;
      return this;
    }`
Use builder-pattern .

2022-08-09 18:25 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/MessageService.java
> +package millom.sandbox;
Update the package name`millom.sandbox.mars.weather.`

2022-08-09 18:27 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/pojo/Sol.java
> +    public SolBuilder(String id, String terrestrialDate, String sol, String ls, String season,
`Replace pojo class with record using builder design pattern.`

2022-08-10 08:59 UTC, TrondTelenor requested changes
Looks even better, still some comments though..

2022-08-10 08:59 UTC, TrondTelenor commented on src/main/java/millom/sandbox/mars/weather/CustomException/DateFormatIncorrectException.java
> +    super(errorMessage);
Fix indentation

2022-08-10 08:59 UTC, TrondTelenor commented on src/main/java/millom/sandbox/mars/weather/record/NasaWeather.java
> +public class NasaWeather {
Please use record

2022-08-10 08:59 UTC, TrondTelenor commented on src/main/java/millom/sandbox/mars/weather/record/Sol.java
> +
To many new-lines

2022-08-10 09:43 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/mars/weather/CustomException/DateFormatIncorrectException.java
> +    super(errorMessage);
Fix indentation.

2022-08-10 09:43 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/mars/weather/record/NasaWeather.java
> +public class NasaWeather {
Update with record.

2022-08-10 09:43 UTC, rajsuman-choubey commented on src/main/java/millom/sandbox/mars/weather/record/Sol.java
> +
Remove new lines.

2022-08-10 10:11 UTC, TrondTelenor approved these changes
Looks good - approved.
Note that the standard is to have 1, exactly one, newline on the end of our files.

2022-08-10 11:22 UTC, rajsuman-choubey commented
Task-3 Create record, map the response, build chain endpoint, add unit..

2022-08-10 11:23 UTC, rajsuman-choubey commented
Task-3 Create record, map the response, build chain endpoint, add unit

2022-08-10 11:23 UTC, merged

2022-08-10 11:51 UTC, rajsuman-choubey commented
Task-3 Create pojos, map the response, build chain endpoint, add unit